### ISSUE TITLE
Please Provide Support for Node JS 12X

### ISSUE THREAD

**Issue by anpriyadar** [romanbalayan/oracledb-prebuilt-for-lambda#1]
Hi  romanbalayan

The package has only limited Support for Node JS 10X.  May i Request you to please provide support for Node JS 12x if possible.

With Regards
Animesh

**Comment by romanbalayan** [comment]
Hi @anpriyadar,

The package should also support nodev12, as it uses the node-oracledb official package v4.0.1.

Or are you asking to support the latest release of node-oracledb v5.0.0

Thanks

**Comment by anpriyadar** [comment]
Thanks @romanbalayan , if package would support node 12 X run time in aws lambda it serve my purpose . 

Thanks a lot 👍
