### ISSUE TITLE
Node-Oracledb 6.2.0 unavailable with project

### ISSUE THREAD

**Issue by wgeiger-barrett** [romanbalayan/oracledb-prebuilt-for-lambda#15]
Shortly after this project was tagged for v6.1.0, it looks like the oracledb team released a v6.2.0: https://github.com/oracle/node-oracledb/issues/1614

Can this version be supported in this project?

**Comment by romanbalayan** [comment]
Hi @wgeiger-barrett,

v6.2.0 and v6.3.0 should now be available.
