### ISSUE TITLE
Node 14 Support?

### ISSUE THREAD

**Issue by herebebogans** [romanbalayan/oracledb-prebuilt-for-lambda#6]
Thanks @romanbalayan - this project is a life saver.

Dont suppose you support node14 as well - it's been recently supported as a runtime in lambda.

**Comment by romanbalayan** [comment]
Hey @herebebogans,

Checked release notes for NodeJS 14 Runtime here: https://docs.aws.amazon.com/lambda/latest/dg/lambda-releases.html. As both both node12.x and 14.x use the same Amazon Linux 2, I presumed that the package would work.

And so I tested, and yup, it works!

```
START RequestId: c77d0926-22ce-4db9-826e-4b4cf0b960f0 Version: $LATEST
2021-05-20T15:15:24.669Z	c77d0926-22ce-4db9-826e-4b4cf0b960f0	INFO	Node Version is: v14.17.0
2021-05-20T15:15:24.671Z	c77d0926-22ce-4db9-826e-4b4cf0b960f0	INFO	Oracle Version is: 50100
END RequestId: c77d0926-22ce-4db9-826e-4b4cf0b960f0
REPORT RequestId: c77d0926-22ce-4db9-826e-4b4cf0b960f0	Init Duration: 0.80 ms	Duration: 515.95 ms	Billed Duration: 600 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
```

**Comment by herebebogans** [comment]
Good to know.
